### PR TITLE
removing deprecated warnings on sms_spec for its, new syntax

### PR DESCRIPTION
**Pull request by JozoSalt**
Updated the syntax for a few tests in sms_spec

### CODE REVIEW

**Comment by sindrenm** [comment]
Love it. Thanks. :smiley:

**Comment by sindrenm** [comment]
Although @timkurvers might have an issue with the lack of space after the `it`s. :stuck_out_tongue:

**Comment by jgorset** [comment]
@timkurvers has issues with everything!

**Comment by jgorset** [comment]
I'm just playing. I like @timkurvers.

**Comment by sindrenm** [comment]
:smiley:

**Pull request merged**
