### PR TITLE
Correct silly space

### PR DESCRIPTION
**Pull request by timkurvers**
:trollface:

### CODE REVIEW

**Comment by sindrenm** [comment]
:trophy:

**Comment by toothfairy** [comment]
No test case for a change? :trollface:

**Comment by sindrenm** [comment]
I suppose test coverage kinda improved in this case.

**Comment by sindrenm** [comment]
Although test coverage is line-based (or rather; statement-based), but whatever.

**Comment by timkurvers** [comment]
Test coverage remained the same since it's a code sample in the README, not a source file :wink:

**Comment by sindrenm** [comment]
Oh! Right. LOL.

**Comment by timkurvers** [comment]
:dancers:

**Pull request merged**
